demo/accounts/urls.py
from django.conf.urls import url

from accounts import views


urlpatterns = [
    url(
        r'^signin/$',
        views.signin,
        name='signin'
    ),
    url(
        r'^profile/$',
        views.profile,
        name='profile'
    )
]

demo/cart/urls.py
from django.urls import path
from cart import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
        views.cart_add,
        name='cart_add'
    ),
    path('remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove'
    ),
]

demo/demo/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import (
    include,
    path
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('social-auth/', include(('social_django.urls', 'social_django'), namespace='social_django')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('signout/', auth_views.LogoutView.as_view(), name="signout"),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
)

# 生產環境不應該用 Django 服務靜態文件
if settings.DEBUG:
    urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT
        )

demo/shop/urls.py
from django.urls import path

from shop import views


urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('list', views.product_list, name='product_list'),
    path('search/', views.product_search, name='product_search'),
    path(
        '<slug:category_slug>/',
        views.product_list,
        name='product_list_by_category'
    ),
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='product_detail'
    ),
]

demo/shop/models.py
from django.db import models
from django.urls import reverse
import django.utils.timezone as timezone


class Category(models.Model):
    # db_index=True: 加索引
    name = models.CharField(
            max_length=200,
            db_index=True
        )
    slug = models.SlugField(
            max_length=200,
            db_index=True,
            unique=True
        )
    image = models.ImageField(
            upload_to='categories/%Y/%m/%d',
            blank=True
        )

    # 定義資料庫 
    class Meta:
        # 排序方式
        # ordering incurs a cost to your database
        ordering = ('name',)
        # 設置 models 直觀可讀的名稱
        verbose_name = 'catgory'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    # on_delete: 定義外來鍵和一對一關係時需要加，避免不一致問題
    #     - CASCADE: 級聯刪除（一般用這個） 
    #     - PROTECT: 會報完整性錯誤
    #     - SET_NULL: 將外來鍵設為 null，前提是可為 null
    #     - SET_DEFAULT: 設定=外來鍵的預設值
    #     - SET(): 呼叫外面的值
    category = models.ForeignKey(
            Category,
            related_name='products',
            on_delete=models.CASCADE  
        )
    name = models.CharField(
            max_length=200,
            db_index=True
        )
    slug = models.SlugField(
            max_length=200,
            db_index=True
        )
    image = models.ImageField(
            upload_to='products/%Y/%m/%d',
            blank=True
        )
    description = models.TextField(blank=True)
    # 不用 FloatField 以避免精度問題
    price = models.DecimalField(
            max_digits=10,
            decimal_places=2
        )
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    # 希望第一次生成時間又可以更改：
    # 1. auto_now_add=True: 第一次保存時生成的時間，之後修改不會更新，所以不能用
    # available = models.DateTimeField(
    #        auto_now_add=True
    #    )
    # 
    # 2. 將 default 設置為當前時間，之後可以修改
    created_at = models.DateTimeField(
            default = timezone.now
        )
    # auto_now=True: 每次修改時，改為最新時間 
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        # 用兩個字段查尋
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

demo/shop/views.py
# -*- coding: UTF-8 -*-
from django.shortcuts import (
    render,
    get_object_or_404
)
from shop.models import (
    Category,
    Product
)
from cart.forms import CartAddProductForm


def homepage(request):
    categories = Category.objects.all()
    return render(
        request,
        'shop/homepage.html',
        {
            'categories': categories
        }
    )

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(
        request,
        'shop/product/list.html',
        {
            'category': category,
            'categories': categories,
            'products': products
        }
    )


def product_detail(request, id, slug):
    product = get_object_or_404(
            Product,
            id=id,
            slug=slug,
            available=True
        )
    cart_product_form = CartAddProductForm()
    return render(
        request,
        'shop/product/detail.html',
        {
            'product': product,
            'cart_product_form': cart_product_form
        }
    )


def product_search(request):
    query = request.GET.get('q')
    if query:
        products = Product.objects.filter(name__contains=query)
    else:
        products = Product.objects.filter(available=True)
    category = None
    categories = Category.objects.all()
    return render(
        request,
        'shop/product/list.html',
        {
            'category': category,
            'categories': categories,
            'products': products,
            'query': query
        }
    )

demo/templates/shop/base.html
{% load static %} {% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Demo - {% block title %}{% endblock%}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" href="{% static 'images/logo.png' %}">

    <!-- Facebook -->
    <meta property="og:url" content="{{ WEBSITE_URL }}" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="{{ WEBSITE_TITLE }}" />
    <meta property="og:description" content="{{ WEBSITE_DESCRIPTION }}" />
    <meta property="og:image" content="{% static 'images/logo.png' %}" />
    <!--/ Facebook -->

    <!-- Schema.org markup for Google+ -->
    <meta itemprop="name" content="{{ WEBSITE_TITLE }}">
    <meta itemprop="description" content="{{ WEB_DESCRIPTION }}">
    <meta itemprop="image" content="{% static 'images/logo.png' %}">
    <!--/ Schema.org markup for Google+ -->

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@ZoeLiao">
    <meta name="twitter:title" content="{{ WEBSITE_TITLE }}">
    <meta name="twitter:description" content="{{ WEBSITE_DESCRIPTION }}">
    <meta name="twitter:creator" content="{{ WEBSITE_AUTHOR }}">
    <!-- Twitter summary card with large image must be at least 280x150px -->
    <meta name="twitter:image:src" content="{% static 'images/logo.png' %}">
    <!--/ Twitter Card data -->

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-151316261-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
   </script>
    <!--/ Global site tag (gtag.js) - Google Analytics -->

    {% block extra_style_sheet %} {% endblock %}
</head>

<body>

    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-light navbar-suspend" id="base-navbar">
        <div class="container">
            <a class="navbar-brand" href="/"><img src="{% static 'images/logo.png' %}" style="width:48px;"></a>

            <button class="navbar-toggler non-border" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		    </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {{ request.name }}
                    <li class="nav-item {% if request.resolver_match.url_name == 'homepage' %}active{% endif %}">
                        <a class="nav-link" href="/" onclick="gaClick('home', 100)">{% trans "Home" %}</a>
                    </li>

                    <!-- cart -->
                    {% with total_items=cart|length %}
                    <li class="nav-item {% if request.resolver_match.url_name == 'cart_detail' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'cart:cart_detail' %}" onclick="gaClick('cart', 200)">{% trans "Cart" %}{% if  total_items  != 0 %}<input type="button" value="{{ total_items }}" class="btn btn-outline-info btn-sm ml-1 cart-button">{% endif %}{% if request.resolver_match.url_name == 'cart_list' %}{% endif %}</a>
                    </li>
                    {% endwith %}
                    <!--/ cart -->

                    <!-- My Account -->
                    <li class="nav-item {% if request.resolver_match.url_name == 'profile' or request.resolver_match.url_name == 'signin' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'accounts:profile' %}" onclick="gaClick('account', 200)">{% trans "My Account" %}</a>
                    </li>
                    <!--/ My Account -->

                    <!-- Admin -->
                    <li class="nav-item" title="account:root, password:admin">
                        <a class="nav-link" href="{% url 'admin:index' %}">{% trans "Admin" %}</a>
                    </li>
                    <!--/ Admin -->

                    <!-- dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="{% url 'accounts:profile' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" onclick="gaClick('language', 200)">{% trans "Language" %}</a>
                        <form action="{% url 'set_language' %}" method="post" id="lang_form">{% csrf_token %}
                            <input name="next" type="hidden" value="{{ redirect_to }}">
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% get_current_language as LANGUAGE_CODE %} {% get_available_languages as LANGUAGES %} {% get_language_info_list for LANGUAGES as languages %} {% for language in languages %}
                                <li>
                                    <button type="submit" name="language" value="{{ language.code }}" class="{% if language.code == LANGUAGE_CODE %}selected{% else%}demo-text-black{% endif %} dropdown-item">
										{{ language.name_local }}
									</button>
                                </li>
                                {% endfor %}
                            </ul>
                        </form>
                        </a>
                    </li>
                    <!--/ dropdown -->
                </ul>

                <!-- search -->
                <form class="form-inline my-2 my-lg-0" action="/search" onclick="gaSearch()">
                    <input class="form-control mr-sm-2" name="q" type="search" placeholder="{% trans 'Search' %}" value="{{ query }}" aria-label="Search" id="nav_search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">{% trans "Search" %}</button>
                </form>
                <!--/ search -->
            </div>
        </div>
    </nav>
    <!--/ navbar -->

    <div id="content" class="mt-5 py-2 min-height-60">
        {% block content %} {% endblock %}
    </div>

    <!-- footer -->
    <div>
        {% include "shop/footer.html" %}
    </div>
    <!--/ footer -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'js/base.js' %}"></script>

    {% block extra_script %}{% endblock %}
    <script>

        function gaClick(eventLabel, value){
            gtag('event', 'Nav Click', {
                'event_category': 'Click',
                'event_label': eventLabel,
                'value': value
            });
        }

        function gaSearch(){
            let searchTerm = $('#nav_search').val();
            gtag('event', 'Nav Search', {
                'event_category': 'Search',
                'event_label': 'search_term',
                'value': searchTerm,
            });
        }

        {% block extra_js %}  {% endblock %}

    </script>
</body>

</html>

demo/templates/shop/carousel.html
{% load static %}
{% load i18n %}
<div class="bd-example">
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static "images/carousel_01.png"%}" class="d-block w-100 h-50vh" alt="carousel_01">
                <div class="carousel-caption d-md-block">
                    <h1 class="carousel-slide-label">DEMO</h1>
                    <p class="carousel-slide-des">{% trans "This is a demo shopping site" %}</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static "images/carousel_02.png"%}" class="d-block w-100 h-50vh" alt="carousel_02">
                <div class="carousel-caption d-md-block">
                    <h1 class="carousel-slide-label">{% trans "Categories" %}</h1>
                    <p class="carousel-slide-des">{% trans "Bags with blue, pink, yellow and green" %}</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static "images/carousel_03.png"%}" class="d-block w-100 h-50vh" alt="carousel_03">
                <div class="carousel-caption d-md-block">
                    <h1 class="carousel-slide-label">{% trans "Products" %}</h1>
                    <p class="carousel-slide-des">{% trans "Blue, pink, yellow, and green bags contain different letters" %}</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

demo/templates/shop/footer.html
{% load i18n %}
<footer id="footer" class="demo-black mt-4">
    <!--Footer Links-->
    <div class="container text-center text-md-left mt-5">
        <div class="row mt-3">
            {% for n in 'demo'%}
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4 mt-4">
                <h6 class="text-uppercase font-weight-bold">
                    <strong class="demo-text-white">{% trans "demo footer" %}</strong>
                </h6>
                <hr class="demo-white full-width">
                {% for m in 'site' %}
                    <p>
                        <a href="#">{{ n }}{{ m }}{{ n }}</a>
                    </p>
                {% endfor %}

            </div>
            {% endfor %}
        </div>
    </div>
    <!--/.Footer Links-->

    <!-- Copyright-->
    <div class="py-3 text-center demo-black demo-text-white">
        © 2019 Copyright:
        <a href="https://github.com/ZoeLiao/python-Django-demo" class="demo-text-white">
            <strong>ZoeLiao</strong>
        </a>
    </div>
    <!--/.Copyright -->

</footer>

demo/templates/shop/homepage.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}

{% block title %}
    {% trans "Homepage" %}
{% endblock %}

{% block content %}

{% include "shop/carousel.html" %}

<!-- jumbotron - Techniques & Tools -->
<div class="jumbotron jumbotron-fluid mt-5 text-center demo-white">
    <div class="container">
        <h1 class="display-5">{% trans "Techniques & Tools" %}</h1>
        <div class="row px-4 mt-5">
            <div class="col-md-3 col-lg-3 col-xl-3 mt-3">
                <img src="{% static 'images/Django.jpg' %}" width="80%" height="70%">
                <p class="lead mt-2">{% trans "Backend - Django" %}</p>
            </div>
            <div class="col-md-3 col-lg-3 col-xl-3 mt-3">
                <img src="{% static 'images/Bootstrap.jpg' %}" width="80%" height="70%">
                <p class="lead mt-2">{% trans "Frontend - Bootstrap" %}</p>
            </div>
            <div class="col-md-3 col-lg-3 col-xl-3 mt-3">
                <img src="{% static 'images/MySQL.png' %}" width="80%" height="70%">
                <p class="lead mt-2">{% trans "Database - MySQL" %}</p>
            </div>
            <div class="col-md-3 col-lg-3 col-xl-3 mt-3">
                <img src="{% static 'images/Redis.png' %}" width="80%" height="70%">
                <p class="lead mt-2">{% trans "Cache - Redis" %}</p>
            </div>
            <div class="col-md-3 col-lg-3 col-xl-3 mt-3">
                <img src="{% static 'images/Celery.jpg' %}" width="80%" height="60%">
                <p class="lead mt-2">{% trans "Sending emails - Celery" %}</p>
            </div>
            <div class="col-md-3 col-lg-3 col-xl-3 mt-3">
                <img src="{% static 'images/github.svg' %}" width="80%" height="60%">
                <p class="lead mt-2">{% trans "Sign in - third-party" %}</p>
            </div>
            <div class="col-md-3 col-lg-3 col-xl-3 mt-3">
                <img src="{% static 'images/Facebook.png' %}" width="80%" height="60%">
                <p class="lead mt-2">{% trans "Sharing - Facebook" %}</p>
            </div>
            <div class="col-md-3 col-lg-3 col-xl-3 mt-3">
                <img src="{% static 'images/docker.jpg' %}" width="80%" height="60%">
                <p class="lead mt-2">{% trans "Deployment - AWS + Docker + uWSGI + NGINX + Certbot" %}</p>
            </div>
        </div>
        <div class="d-flex justify-content-center mt-4">
            <button class="btn btn-info" onclick="window.location.href='https://github.com/ZoeLiao/python-Django-demo'">{% trans "Source Code" %}</button>
        </div>
    </div>
</div>
<!--/ jumbotron - Techniques & Tools -->

<!-- jumbotron - About -->
<div class="jumbotron jumbotron-fluid mt-5 text-center demo-sky-blue">
    <div class="container">
        <h1 class="display-5">{% trans "About" %}</h1>
        <p class="lead">{% trans "This is a demo shopping site, you can sign in in with third-party accounts,<br> add goods to your cart, and receive an email after checking out." %}</p>
    </div>
</div>
<!--/ jumbotron - About -->

<!-- categories -->
<div class="container-fluid px-5 mt-5">
    <div class="mt-5 text-center">
        <h1 class="display-5">{% trans "Categories" %}</h1>
    </div>

    <div class="row px-4 mt-5">
        {% for category in categories %}
            <div class="col-md-3 col-lg-3 col-xl-3 mt-3">
                <div class="card">
                    <div class="demo-grey">
                        <a href="{{ category.get_absolute_url }}">
                            <img class="card-img-top" src="{% if category.image %}{{ category.image.url }}{% else %}{% static "images/no_image.png" %}{% endif %}"/>
                        </a>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">
                            <a href="{{ category.get_absolute_url }}" class="demo-link demo-text-black">
                                {{ category }}
                            </a>
                        </h5>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="d-flex justify-content-center mt-4">
        <button class="btn btn-info" onclick="window.location.href='{% url 'shop:product_list' %}'">{% trans "See More" %}</button>
    </div>
</div>
<!-- categories -->

<!-- jumbotron - Contact Me -->
<div class="jumbotron jumbotron-fluid mt-5 text-center demo-blue padding-bottom-sm">
    <div class="container">
        <h1 class="display-5">{% trans "Contact Me" %}</h1>
        <div class="row mt-4">
            <div class="col-md-3 col-lg-3 col-xl-3 mt-3" title="github">
                <a href="https://github.com/ZoeLiao">
                    <img src="{% static 'images/github.svg' %}" width="60%" height="60%">
                </s>
            </div>
            <div class="col-md-3 col-lg-3 col-xl-3 mt-3" title="medium">
                <a href="https://medium.com/@zoejoyuliao">
                    <img src="{% static 'images/medium.svg' %}" width="60%" height="60%">
                </s>
            </div>
            <div class="col-md-3 col-lg-3 col-xl-3 mt-3" title="blog">
                <a href="https://zoeliao.netlify.com/">
                    <img src="{% static 'images/netlify.png' %}" width="50%" height="60%">
                </a>
            </div>
            <div class="col-md-3 col-lg-3 col-xl-3 mt-3" title="email">
                <a href="mailto:zoejoyuliao@gmail.com">
                    <img src="{% static 'images/mail.png' %}" width="40%" height="50%">
                </a>
            </div>
        </div>
    </div>
</div>
<!--/ jumbotron - Contact Me -->

<!-- Demo Map -->
<div class="container-fluid px-5">
    <div class="mt-5 text-center mt-4">
        <h1 class="display-5">{% trans "Demo Map" %}</h1>
        <br>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d934404.1335401109!2d120.43461878228617!3d23.818024864465542!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x346eb26c6c1036a5%3A0x8d37b2ba3f8f326e!2z5r-B5rC05rqq!5e0!3m2!1szh-TW!2stw!4v1568036171629!5m2!1szh-TW!2stw" width="100%" height="600rem" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
    </div>
</div>
<!--/ Demo Map -->
{% endblock %}